// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

const apiKeyA = String.fromEnvironment("FIREBASE_API_KEY_ANDROID", defaultValue: "");
const apiKeyIos = String.fromEnvironment("FIREBASE_API_KEY_IOS", defaultValue: "");
const appIdA = String.fromEnvironment("FIREBASE_APP_ID_ANDROID", defaultValue: "");
const appIdIos = String.fromEnvironment("FIREBASE_APP_ID_IOS", defaultValue: "");
const msgSenderId = String.fromEnvironment("FIREBASE_MESSAGING_SENDER_ID", defaultValue: "");
const projectId = String.fromEnvironment("FIREBASE_PROJECT_ID", defaultValue: "");
const storageBucket = String.fromEnvironment("FIREBASE_STORAGE_BUCKET", defaultValue: "");
const iosBundleId = String.fromEnvironment("FIREBASE_IOS_BUNDLE_ID", defaultValue: "");

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: apiKeyA,
    appId: appIdA,
    messagingSenderId: msgSenderId,
    projectId: projectId,
    storageBucket: storageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: apiKeyIos,
    appId: appIdIos,
    messagingSenderId: msgSenderId,
    projectId: projectId,
    storageBucket: storageBucket,
    iosBundleId: iosBundleId,
  );
}
